
CREATE SCHEMA IF NOT EXISTS dbo;
SET search_path TO dbo, public;


CREATE TABLE IF NOT EXISTS dbo.roles (
    roleid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rolename TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS dbo.users (
    userid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname VARCHAR(50) NOT NULL,
    email TEXT NOT NULL UNIQUE,
    phone TEXT,
    avatar VARCHAR(255),
    dateofbirth DATE,
    gender TEXT,
    passwordhash TEXT NOT NULL,
    isactive BOOLEAN DEFAULT TRUE,
    isdeleted BOOLEAN DEFAULT FALSE,
    createdat TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    provider TEXT NOT NULL DEFAULT 'LOCAL' CHECK (provider IN ('LOCAL', 'GOOGLE', 'FACEBOOK')),
    backgroundimage VARCHAR(255),
    preferredpaymentmethod VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS dbo.publishers (
    publisherid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publishername VARCHAR(150) NOT NULL,
    contactemail TEXT,
    address VARCHAR(255),
    isdeleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS dbo.categories (
    categoryid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoryname VARCHAR(100) NOT NULL,
    parentid BIGINT,
    isdeleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_categories_parent
        FOREIGN KEY (parentid) REFERENCES dbo.categories (categoryid)
);

CREATE TABLE IF NOT EXISTS dbo.authors (
    authorid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorname VARCHAR(150) NOT NULL,
    biography TEXT,
    isdeleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS dbo.promotions (
    promotionid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotionname VARCHAR(50),
    discountpercent INTEGER,
    startdate TIMESTAMPTZ,
    enddate TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS dbo.vouchers (
    voucherid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    description VARCHAR(255),
    discounttype VARCHAR(20) NOT NULL,
    discountvalue NUMERIC(19,2) NOT NULL,
    minorderamount NUMERIC(19,2) DEFAULT 0,
    maxdiscountamount NUMERIC(19,2),
    usagelimit INTEGER,
    usedcount INTEGER DEFAULT 0,
    startdate TIMESTAMPTZ NOT NULL,
    enddate TIMESTAMPTZ NOT NULL,
    isactive BOOLEAN DEFAULT TRUE,
    createdat TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- Product/catalog tables
-- =========================

CREATE TABLE IF NOT EXISTS dbo.books (
    bookid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    isbn TEXT,
    description TEXT,
    price NUMERIC(19,2) NOT NULL,
    publisherid BIGINT,
    publishyear INTEGER,
    language VARCHAR(50),
    soldcount INTEGER DEFAULT 0,
    isactive BOOLEAN DEFAULT TRUE,
    isdeleted BOOLEAN DEFAULT FALSE,
    createdat TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_books_publisher
        FOREIGN KEY (publisherid) REFERENCES dbo.publishers (publisherid)
);

CREATE TABLE IF NOT EXISTS dbo.inventories (
    bookid BIGINT PRIMARY KEY,
    quantity INTEGER NOT NULL,
    reserved INTEGER DEFAULT 0,
    CONSTRAINT fk_inventories_book
        FOREIGN KEY (bookid) REFERENCES dbo.books (bookid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dbo.bookimages (
    imageid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookid BIGINT NOT NULL,
    imageurl VARCHAR(255),
    ismain BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_bookimages_book
        FOREIGN KEY (bookid) REFERENCES dbo.books (bookid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dbo.categoriesimages (
    imageid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoryid BIGINT NOT NULL,
    imageurl VARCHAR(255) NOT NULL,
    ismain BOOLEAN DEFAULT FALSE,
    isdeleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_categoriesimages_category
        FOREIGN KEY (categoryid) REFERENCES dbo.categories (categoryid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dbo.bookauthors (
    bookid BIGINT NOT NULL,
    authorid BIGINT NOT NULL,
    PRIMARY KEY (bookid, authorid),
    CONSTRAINT fk_bookauthors_book
        FOREIGN KEY (bookid) REFERENCES dbo.books (bookid) ON DELETE CASCADE,
    CONSTRAINT fk_bookauthors_author
        FOREIGN KEY (authorid) REFERENCES dbo.authors (authorid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dbo.bookcategories (
    bookid BIGINT NOT NULL,
    categoryid BIGINT NOT NULL,
    PRIMARY KEY (bookid, categoryid),
    CONSTRAINT fk_bookcategories_book
        FOREIGN KEY (bookid) REFERENCES dbo.books (bookid) ON DELETE CASCADE,
    CONSTRAINT fk_bookcategories_category
        FOREIGN KEY (categoryid) REFERENCES dbo.categories (categoryid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dbo.promotionbooks (
    promotionid BIGINT NOT NULL,
    bookid BIGINT NOT NULL,
    PRIMARY KEY (promotionid, bookid),
    CONSTRAINT fk_promotionbooks_promotion
        FOREIGN KEY (promotionid) REFERENCES dbo.promotions (promotionid) ON DELETE CASCADE,
    CONSTRAINT fk_promotionbooks_book
        FOREIGN KEY (bookid) REFERENCES dbo.books (bookid) ON DELETE CASCADE
);

-- =========================
-- User/cart/checkout tables
-- =========================

CREATE TABLE IF NOT EXISTS dbo.userroles (
    userid BIGINT NOT NULL,
    roleid BIGINT NOT NULL,
    PRIMARY KEY (userid, roleid),
    CONSTRAINT fk_userroles_user
        FOREIGN KEY (userid) REFERENCES dbo.users (userid) ON DELETE CASCADE,
    CONSTRAINT fk_userroles_role
        FOREIGN KEY (roleid) REFERENCES dbo.roles (roleid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dbo.carts (
    cartid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid BIGINT NOT NULL UNIQUE,
    createdat TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_carts_user
        FOREIGN KEY (userid) REFERENCES dbo.users (userid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dbo.cartitems (
    cartid BIGINT NOT NULL,
    bookid BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    PRIMARY KEY (cartid, bookid),
    CONSTRAINT fk_cartitems_cart
        FOREIGN KEY (cartid) REFERENCES dbo.carts (cartid) ON DELETE CASCADE,
    CONSTRAINT fk_cartitems_book
        FOREIGN KEY (bookid) REFERENCES dbo.books (bookid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dbo.useraddresses (
    addressid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid BIGINT NOT NULL,
    receivername VARCHAR(100),
    addressline VARCHAR(255),
    province VARCHAR(100),
    district VARCHAR(100),
    ward VARCHAR(100),
    addresstype VARCHAR(50) DEFAULT 'Home',
    phone TEXT,
    isdefault BOOLEAN DEFAULT FALSE,
    isdeleted BOOLEAN DEFAULT FALSE,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    CONSTRAINT fk_useraddresses_user
        FOREIGN KEY (userid) REFERENCES dbo.users (userid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dbo.emailverificationtokens (
    tokenid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL,
    expiredat TIMESTAMPTZ NOT NULL,
    isused BOOLEAN DEFAULT FALSE,
    createdat TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_emailtokens_user
        FOREIGN KEY (userid) REFERENCES dbo.users (userid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dbo.notifications (
    notificationid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    type VARCHAR(50),
    isread BOOLEAN DEFAULT FALSE,
    createdat TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user
        FOREIGN KEY (userid) REFERENCES dbo.users (userid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dbo.wishlists (
    userid BIGINT NOT NULL,
    bookid BIGINT NOT NULL,
    createdat TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (userid, bookid),
    CONSTRAINT fk_wishlists_user
        FOREIGN KEY (userid) REFERENCES dbo.users (userid) ON DELETE CASCADE,
    CONSTRAINT fk_wishlists_book
        FOREIGN KEY (bookid) REFERENCES dbo.books (bookid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dbo.reviews (
    reviewid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookid BIGINT NOT NULL,
    userid BIGINT NOT NULL,
    rating INTEGER,
    comment TEXT,
    createdat TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reviews_book
        FOREIGN KEY (bookid) REFERENCES dbo.books (bookid) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_user
        FOREIGN KEY (userid) REFERENCES dbo.users (userid) ON DELETE CASCADE
);

-- =========================
-- Orders/payments tables
-- =========================

CREATE TABLE IF NOT EXISTS dbo.orders (
    orderid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid BIGINT NOT NULL,
    addressid BIGINT NOT NULL,
    totalamount NUMERIC(19,2),
    currentstatus VARCHAR(50),
    canceledreason VARCHAR(255),
    canceledat TIMESTAMPTZ,
    createdat TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    completedat TIMESTAMPTZ,
    voucherid BIGINT,
    paymentmethod VARCHAR(50),
    shippingfee NUMERIC(19,2) DEFAULT 0,
    discountamount NUMERIC(19,2) DEFAULT 0,
    note VARCHAR(255),
    CONSTRAINT fk_orders_user
        FOREIGN KEY (userid) REFERENCES dbo.users (userid),
    CONSTRAINT fk_orders_address
        FOREIGN KEY (addressid) REFERENCES dbo.useraddresses (addressid),
    CONSTRAINT fk_orders_voucher
        FOREIGN KEY (voucherid) REFERENCES dbo.vouchers (voucherid)
);

CREATE TABLE IF NOT EXISTS dbo.orderitems (
    orderid BIGINT NOT NULL,
    bookid BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    price NUMERIC(19,2) NOT NULL,
    PRIMARY KEY (orderid, bookid),
    CONSTRAINT fk_orderitems_order
        FOREIGN KEY (orderid) REFERENCES dbo.orders (orderid) ON DELETE CASCADE,
    CONSTRAINT fk_orderitems_book
        FOREIGN KEY (bookid) REFERENCES dbo.books (bookid)
);

CREATE TABLE IF NOT EXISTS dbo.payments (
    paymentid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orderid BIGINT NOT NULL,
    provider VARCHAR(100),
    transactioncode VARCHAR(150),
    amount NUMERIC(19,2) NOT NULL,
    status VARCHAR(50) DEFAULT 'Pending',
    responsedata TEXT,
    paymentdate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_order
        FOREIGN KEY (orderid) REFERENCES dbo.orders (orderid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dbo.shipping (
    shippingid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orderid BIGINT NOT NULL,
    shippingprovider VARCHAR(100),
    trackingnumber VARCHAR(150),
    shippingstatus VARCHAR(50),
    estimateddeliverydate TIMESTAMPTZ,
    actualdeliverydate TIMESTAMPTZ,
    shippedat TIMESTAMPTZ,
    CONSTRAINT fk_shipping_order
        FOREIGN KEY (orderid) REFERENCES dbo.orders (orderid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dbo.orderstatushistory (
    historyid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orderid BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    note VARCHAR(255),
    changedat TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orderstatushistory_order
        FOREIGN KEY (orderid) REFERENCES dbo.orders (orderid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dbo.voucherusage (
    voucherusageid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucherid BIGINT NOT NULL,
    userid BIGINT NOT NULL,
    orderid BIGINT,
    usedat TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_voucherusage_voucher
        FOREIGN KEY (voucherid) REFERENCES dbo.vouchers (voucherid),
    CONSTRAINT fk_voucherusage_user
        FOREIGN KEY (userid) REFERENCES dbo.users (userid),
    CONSTRAINT fk_voucherusage_order
        FOREIGN KEY (orderid) REFERENCES dbo.orders (orderid)
);

-- =========================
-- Helpful indexes for common queries
-- =========================

CREATE INDEX IF NOT EXISTS idx_books_isactive_isdeleted ON dbo.books (isactive, isdeleted);
CREATE INDEX IF NOT EXISTS idx_books_createdat ON dbo.books (createdat DESC);
CREATE INDEX IF NOT EXISTS idx_books_soldcount ON dbo.books (soldcount DESC);
CREATE INDEX IF NOT EXISTS idx_orders_user_createdat ON dbo.orders (userid, createdat DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status ON dbo.orders (currentstatus);
CREATE INDEX IF NOT EXISTS idx_reviews_book ON dbo.reviews (bookid, createdat DESC);
CREATE INDEX IF NOT EXISTS idx_useraddresses_user_default ON dbo.useraddresses (userid, isdefault);
CREATE INDEX IF NOT EXISTS idx_emailtokens_token ON dbo.emailverificationtokens (token);

-- =========================
-- Minimal seed data
-- =========================

-- Roles required by backend auth flow.
INSERT INTO dbo.roles (roleid, rolename) VALUES
    (1, 'ROLE_ADMIN'),
    (2, 'ROLE_CUSTOMER')
ON CONFLICT (roleid) DO UPDATE SET rolename = EXCLUDED.rolename;

INSERT INTO dbo.roles (rolename)
VALUES ('ADMIN'), ('CUSTOMER')
ON CONFLICT (rolename) DO NOTHING;

-- Password for both seeded accounts: Admin@123
INSERT INTO dbo.users (
    userid, fullname, email, passwordhash, isactive, isdeleted, createdat, provider
) VALUES
    (1, 'System Admin', 'admin@bookstore.local', '$2a$10$edQk00AuP4j0O2fyQCukoOxxyeQA3uu73yX2TNGU1gQc5PIou2cne', TRUE, FALSE, CURRENT_TIMESTAMP, 'LOCAL'),
    (2, 'Demo Customer', 'customer@bookstore.local', '$2a$10$edQk00AuP4j0O2fyQCukoOxxyeQA3uu73yX2TNGU1gQc5PIou2cne', TRUE, FALSE, CURRENT_TIMESTAMP, 'LOCAL')
ON CONFLICT (userid) DO NOTHING;

INSERT INTO dbo.userroles (userid, roleid) VALUES
    (1, 1),
    (2, 2)
ON CONFLICT (userid, roleid) DO NOTHING;

-- Minimal catalog so homepage has visible data.
INSERT INTO dbo.publishers (publisherid, publishername, isdeleted)
VALUES (1, 'Bookstore Default Publisher', FALSE)
ON CONFLICT (publisherid) DO NOTHING;

INSERT INTO dbo.categories (categoryid, categoryname, isdeleted)
VALUES (1, 'General', FALSE)
ON CONFLICT (categoryid) DO NOTHING;

INSERT INTO dbo.authors (authorid, authorname, isdeleted)
VALUES (1, 'Unknown Author', FALSE)
ON CONFLICT (authorid) DO NOTHING;

INSERT INTO dbo.books (
    bookid, title, slug, isbn, description, price, publisherid, publishyear, language,
    soldcount, isactive, isdeleted, createdat
) VALUES (
    1,
    'Demo Book',
    'demo-book',
    'DEMO-ISBN-001',
    'Seeded demo book for initial project startup.',
    99000,
    1,
    EXTRACT(YEAR FROM CURRENT_DATE),
    'Vietnamese',
    0,
    TRUE,
    FALSE,
    CURRENT_TIMESTAMP
)
ON CONFLICT (bookid) DO NOTHING;

INSERT INTO dbo.inventories (bookid, quantity, reserved)
VALUES (1, 100, 0)
ON CONFLICT (bookid) DO UPDATE
SET quantity = EXCLUDED.quantity,
    reserved = EXCLUDED.reserved;

INSERT INTO dbo.bookimages (imageid, bookid, imageurl, ismain)
VALUES (1, 1, 'default_book_image.jpg', TRUE)
ON CONFLICT (imageid) DO NOTHING;

INSERT INTO dbo.bookcategories (bookid, categoryid)
VALUES (1, 1)
ON CONFLICT (bookid, categoryid) DO NOTHING;

INSERT INTO dbo.bookauthors (bookid, authorid)
VALUES (1, 1)
ON CONFLICT (bookid, authorid) DO NOTHING;

INSERT INTO dbo.carts (cartid, userid, createdat)
VALUES (1, 2, CURRENT_TIMESTAMP)
ON CONFLICT (cartid) DO NOTHING;

INSERT INTO dbo.useraddresses (
    addressid, userid, receivername, addressline, province, district, ward,
    addresstype, phone, isdefault, isdeleted
)
VALUES (
    1, 2, 'Demo Customer', '123 Demo Street', 'Ho Chi Minh', 'District 1', 'Ben Nghe',
    'Home', '0900000000', TRUE, FALSE
)
ON CONFLICT (addressid) DO NOTHING;

-- =========================
-- Keep all identity sequences in sync after explicit ID inserts
-- =========================

SELECT setval(pg_get_serial_sequence('dbo.roles', 'roleid'), COALESCE((SELECT MAX(roleid) FROM dbo.roles), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.users', 'userid'), COALESCE((SELECT MAX(userid) FROM dbo.users), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.publishers', 'publisherid'), COALESCE((SELECT MAX(publisherid) FROM dbo.publishers), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.categories', 'categoryid'), COALESCE((SELECT MAX(categoryid) FROM dbo.categories), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.authors', 'authorid'), COALESCE((SELECT MAX(authorid) FROM dbo.authors), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.promotions', 'promotionid'), COALESCE((SELECT MAX(promotionid) FROM dbo.promotions), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.vouchers', 'voucherid'), COALESCE((SELECT MAX(voucherid) FROM dbo.vouchers), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.books', 'bookid'), COALESCE((SELECT MAX(bookid) FROM dbo.books), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.bookimages', 'imageid'), COALESCE((SELECT MAX(imageid) FROM dbo.bookimages), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.categoriesimages', 'imageid'), COALESCE((SELECT MAX(imageid) FROM dbo.categoriesimages), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.carts', 'cartid'), COALESCE((SELECT MAX(cartid) FROM dbo.carts), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.useraddresses', 'addressid'), COALESCE((SELECT MAX(addressid) FROM dbo.useraddresses), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.emailverificationtokens', 'tokenid'), COALESCE((SELECT MAX(tokenid) FROM dbo.emailverificationtokens), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.notifications', 'notificationid'), COALESCE((SELECT MAX(notificationid) FROM dbo.notifications), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.reviews', 'reviewid'), COALESCE((SELECT MAX(reviewid) FROM dbo.reviews), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.orders', 'orderid'), COALESCE((SELECT MAX(orderid) FROM dbo.orders), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.payments', 'paymentid'), COALESCE((SELECT MAX(paymentid) FROM dbo.payments), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.shipping', 'shippingid'), COALESCE((SELECT MAX(shippingid) FROM dbo.shipping), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.orderstatushistory', 'historyid'), COALESCE((SELECT MAX(historyid) FROM dbo.orderstatushistory), 1), true);
SELECT setval(pg_get_serial_sequence('dbo.voucherusage', 'voucherusageid'), COALESCE((SELECT MAX(voucherusageid) FROM dbo.voucherusage), 1), true);
